export { default as HomeSlice } from './HomeSlice'
export { default as FullWidthImage } from './FullWidthImage'
export { default as ImageGallery } from './ImageGallery'
export { default as FeaturedImage } from './FeaturedImage'
export { default as QuoteSlice } from './QuoteSlice'
export { default as TextSlice } from './TextSlice'